version: '3.7'
services:
  web:
    image: nikaapots/lab4:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lab3/:/usr/src/lab3
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nika_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django_db
volumes:
  postgres_data: