# Generated by Django 3.2.3 on 2022-06-01 20:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='uploads/', blank=True, null=True)
        ),
    ]
