# Generated by Django 3.2.3 on 2022-06-01 20:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
