# Generated by Django 3.2.3 on 2022-06-03 14:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220603_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
